// ========================================================================
// background.js — Service Worker Orchestrator
// ------------------------------------------------------------------------
// 改造后只做三件事：
//   1) 拿到当前 tab 的 repoInfo
//   2) 调度 Agent（runPerception / runResolve / runDecision / runVerify）
//   3) 转发消息给 sidepanel
// 所有重活都在 skills / rag / resolver / verifier / agent 里
// ========================================================================

import {
  runPerception,
  runResolve,
  runDecisionOnly,
} from "./agent.js";
import { fetchWithTimeout } from "./utils.js";

// 打开侧边栏的行为
chrome.sidePanel
  .setPanelBehavior({ openPanelOnActionClick: true })
  .catch((err) => console.error(err));

// Session state（service worker 重启会丢，但单次分析足够）
let LAST_CTX = null;

// 监听 sidepanel 的消息
chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => {
  if (msg.type === "SCAN_REPO") {
    runScanPipeline().catch((err) => {
      chrome.runtime.sendMessage({
        type: "UPDATE_STATUS",
        text: `❌ Error: ${err.message}`,
        isError: true,
      });
    });
    return true;
  }

  if (msg.type === "ANALYZE_WITH_LLM") {
    runLLMPipeline().catch((err) => {
      chrome.runtime.sendMessage({
        type: "UPDATE_STATUS",
        text: `❌ AI Error: ${err.message}`,
        isError: true,
      });
    });
    return true;
  }
});

// ========================================================================
// 阶段 1: Scan + Perception + Resolve（无需 LLM 就能完成）
// ========================================================================
async function runScanPipeline() {
  await sendGitHubUser();

  const tabs = await chrome.tabs.query({
    active: true,
    lastFocusedWindow: true,
  });
  const tab = tabs[0];
  if (!tab || !tab.url) throw new Error("No active tab found.");
  if (!tab.url.includes("github.com")) throw new Error("Not a GitHub page.");

  chrome.runtime.sendMessage({
    type: "UPDATE_STATUS",
    text: "🔧 Injecting content script...",
  });

  try {
    await chrome.scripting.executeScript({
      target: { tabId: tab.id },
      files: ["content.js"],
    });
  } catch (e) {
    // 已注入则忽略
  }

  const repoInfo = await chrome.tabs.sendMessage(tab.id, {
    type: "GET_REPO_INFO",
  });
  if (!repoInfo || !repoInfo.ok) throw new Error("Failed to parse repo info.");

  chrome.runtime.sendMessage({
    type: "AGENT_START",
    repoInfo,
  });

  // Perception
  let ctx = await runPerception(repoInfo);

  // 广播 perception 摘要
  chrome.runtime.sendMessage({
    type: "PERCEPTION_DONE",
    summary: {
      imports: ctx.imports.length,
      candidates: ctx.imports,
      projectType: ctx.projectType.type,
      projectTypeRanked: ctx.projectType.ranked,
      pythonVersion: ctx.signals.pythonVersion,
      cuda: ctx.signals.cuda,
      baseImage: ctx.signals.baseImage,
      osDeps: ctx.signals.osDeps,
      manifestFound: ctx.manifest.found,
      entrypoint: ctx.entrypoint.suggested,
      entrypointCmd: ctx.entrypoint.cmd,
    },
    repoInfo,
  });

  // Resolve（六级证据）
  ctx = await runResolve(ctx);

  chrome.runtime.sendMessage({
    type: "RESOLVE_DONE",
    evidence: Object.values(ctx.resolve.resolved).map((r) => ({
      package: r.package,
      version: r.version,
      source: r.source,
      confidence: r.confidence,
      level: r.level,
    })),
    sourceBreakdown: ctx.resolve.sourceBreakdown,
    avgConfidence: ctx.resolve.avgConfidence,
  });

  // 生成增强版 draft
  const draftReq = buildDraftRequirements(ctx);
  const draftDock = buildDraftDockerfile(ctx);

  chrome.runtime.sendMessage({
    type: "SCAN_COMPLETE",
    data: {
      candidates: ctx.imports,
      repoInfo: ctx.repoInfo,
      draftRequirements: draftReq,
      draftDockerfile: draftDock,
    },
  });

  LAST_CTX = ctx;
  return ctx;
}

// 根据 resolver 结果构造 draft requirements（不经 LLM）
function buildDraftRequirements(ctx) {
  const lines = ["# [Draft] Generated by Agent — evidence-ranked versions"];
  lines.push(`# Project type: ${ctx.projectType.type}`);
  lines.push(`# Python target: ${ctx.signals.pythonVersion}`);
  lines.push("");

  for (const r of Object.values(ctx.resolve.resolved)) {
    if (r.version) {
      const confPct = (r.confidence * 100).toFixed(0);
      lines.push(`${r.package}==${r.version}  # [${r.source} ${confPct}%]`);
    } else {
      lines.push(`${r.package}  # [UNKNOWN — needs LLM]`);
    }
  }
  return lines.join("\n");
}

// 根据 perception 结果构造一个"基本可运行"的 draft Dockerfile
function buildDraftDockerfile(ctx) {
  const py = ctx.signals.pythonVersion || "3.11";
  const cuda = ctx.signals.cuda;
  const ep = ctx.entrypoint.cmd;

  const baseImage = cuda
    ? `nvidia/cuda:${cuda}-cudnn-runtime-ubuntu22.04`
    : `python:${py}-slim`;

  const sysDepsFromSkill = ctx.signals.osDeps || [];
  const aptLine = sysDepsFromSkill.length
    ? `RUN apt-get update && apt-get install -y --no-install-recommends ${sysDepsFromSkill.join(
        " "
      )} && rm -rf /var/lib/apt/lists/*\n\n`
    : "";

  return `# Draft Dockerfile — produced by Agent (pre-LLM)
# Project type: ${ctx.projectType.type}
# Evidence avg confidence: ${(ctx.resolve.avgConfidence * 100).toFixed(0)}%
# Run AI step for refinement (explanations, CMD polishing).

FROM ${baseImage}

WORKDIR /app

${aptLine}COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

${ep}
`;
}

// ========================================================================
// 阶段 2: LLM Decision + Verify
// ========================================================================
async function runLLMPipeline() {
  if (!LAST_CTX) throw new Error("Run scan first.");

  const { llmConfig } = await chrome.storage.local.get(["llmConfig"]);
  if (!llmConfig || !llmConfig.apiKey) throw new Error("Missing LLM API key. Open Settings.");

  await runDecisionOnly(LAST_CTX, llmConfig);
}

// ========================================================================
// GitHub user fetch（保留，供 UI 展示）
// ========================================================================
async function sendGitHubUser() {
  const { githubToken } = await chrome.storage.local.get(["githubToken"]);
  const headers = { Accept: "application/vnd.github+json" };
  if (githubToken) headers.Authorization = `Bearer ${githubToken}`;

  try {
    const res = await fetchWithTimeout(
      "https://api.github.com/user",
      { headers },
      5000
    );
    if (!res.ok) {
      chrome.runtime.sendMessage({ type: "GITHUB_USER", user: null });
      return;
    }
    const data = await res.json();
    chrome.runtime.sendMessage({
      type: "GITHUB_USER",
      user: { login: data.login, avatar: data.avatar_url },
    });
  } catch {
    chrome.runtime.sendMessage({ type: "GITHUB_USER", user: null });
  }
}
